### PR TITLE
Reduce backend gateway timeouts

### LINKED ISSUE #24: Server-side errors when re-running a new protocol on all models
I got this error when re-running all experiments with a new version of a protocol on scrambler

image

@jonc125 saw  `504 Gateway Time-out` in the server logs:
> "Seems the back-end CGI gets overwhelmed with too many requests at once so doesn't respond to them all in time"

### PR DESCRIPTION
**Pull request by jonc125**
Fix #24 (for now) by running more fcgiwrap processes and increasing timeouts. When we move the fc-runner to a proper wsgi app rather than old-fashioned CGI this should help further (see https://github.com/ModellingWebLab/fc-runner/issues/6).

### CODE REVIEW

**Comment by jonc125** [comment]
Tested on my local dev deployment. Happy for me to deploy on scrambler?

**Comment by mirams** [comment]
Yeah, nothing mission critical going on at the moment as far as I know

**Comment by jonc125** [comment]
OK, deployed on scrambler. See if you can make it break again @mirams :)

**Comment by jonc125** [comment]
Gary says "Much better experiment re-running with new model version - a lot faster and no errors evident."

**Pull request merged**
